### ISSUE TITLE
a problem in make libgbvs

### ISSUE THREAD

**Issue by cjhkeep** [Telecommunication-Telemedia-Assessment/GBVS360-BMS360-ProSal#1]
Makefile of libgbvs：

```
CC = clang++
CL = ar
CLFLAGS = rvs

CFLAGS = -W -Wall -g -std=c++14 \
                         -I/usr/local/include \
                         -I../liblinper/src \
                         -I../libmeanshift/src

LDFLAGS = -L/usr/local/lib \
          -L../liblinper/bin \
          -I/usr/local/include \
                  -L../libmeanshift/bin \
                  -lopencv_core -lopencv_imgproc -lopencv_objdetect -lopencv_highgui -lopencv_imgcodecs \
                  -lboost_program_options -lboost_exception -lboost_thread -lboost_system \
                  -lfftw3 \
                  -llinper \
                  -lmean_shift
```

------------------------
error msg:
```
clang++ -W -Wall -g -std=c++14 -I/usr/local/include -I../liblinper/src -I../libmeanshift/src  -o src/GBVS.o -c src/GBVS.cpp 
clang++ -W -Wall -g -std=c++14 -I/usr/local/include -I../liblinper/src -I../libmeanshift/src  -o src/main.o -c src/main.cpp 
clang++ -L/usr/local/lib -L../liblinper/bin -I/usr/local/include -I../liblinper/src -L../libmeanshift/bin -lopencv_core -lopencv_imgproc -lopencv_objdetect -lopencv_highgui -lopencv_imgcodecs -lboost_program_options -lboost_exception -lboost_thread -lboost_system -lfftw3 -llinper -lmean_shift -o bin/gbvs src/GBVS.o src/main.o src/fftw++.cc
src/GBVS.o： ‘GBVS::getPerspectiveFeatureJob(cv::Mat const&, cv::Mat&, double*) const’ ：
/home/GBVS360-BMS360-ProSal-master/lib/libgbvs/src/GBVS.cpp:1644： ‘vanishingLineFeatureMapF64C3(cv::Mat const&, double*)’ no define the include
src/GBVS.o：in ‘GBVS::segmentationFeature(cv::Mat const&) const’：
/home/GBVS360-BMS360-ProSal-master/lib/libgbvs/src/GBVS.cpp:1826：‘msseg_f(cv::Mat&, float, float, unsigned int, cv::Mat&)’no define the include
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by plebreton** [comment]
Hi,

Are you sure that the error message is complete and some part are not missing due to a problem when you did the copy/paste? The error message looks a bit odd, "no define the include" does not seems to be proper English. 

From the path, I am guessing you are using linux. Could you try to replace clang++ by g++ ?

**Comment by cjhkeep** [comment]
@plebreton thx your quick reply. It's some part of the error msg. Because the whole msg contain some character which not English.By the way, I somewhat fix the problem and meet a new problem.
I using clang in ubuntu16.04, I will try g++ later
the error msg is about undefine include function(those function is in the /lib/), it seem it did't include the code right
**the first problem**
in /lib/libgbvs/Makefile
turn 
`SRC = $(wildcard src/*.cpp src/*.cc)`
to
```
SRC = $(wildcard src/*.cpp src/*.cc ../liblinper/src/*.cpp ../liblinper/lsd/src/*.cpp \
     ../liblinper/jlinkage/src/*.cpp ../libmeanshift/src/*.cpp \
     ../libmeanshift/src/segm/*.cpp ../libmeanshift/src/edge/*.cpp)
```

I not familar with the makefile, and I not sure it is right 2 do that. but it can success build the libgbvs.a

**the sec problem**
in GBVS360-BMS360-ProSal-master/lib/libgnomonic/lib/libinter/src, the library is build by *.c，
that make it can't deal with the messure  using in the first problem.

I alread build in windows just cost several hours and all generate well.
It seems it is more  convinent in windows.

**Comment by plebreton** [comment]
To be honest, I only tested the build process on macOS and Windows. But there is no particular reason it would not compile on Linux.

But I think I understand what is happening. The general process of building the library was to generate .o from .cpp, and then I generate libraries ".a" using the tool "ar". 

And before building libgbvs, you need to have liblinper and libmeanshift to be built. 

So I am guessing in my build chain, it fails to build the ".a" files, and then cannot link it while building libgbvs, and then you get the linker error. And indeed, if you do as you did and add the source of all files from the liblinper & libmeanshift related stuff, then it gets everything it needs. 

Can you check if you have ".a" files in the folders: 
- GBVS360-BMS360-ProSal/lib/liblinper/bin
- GBVS360-BMS360-ProSal/lib/libmeanshift/bin

I will have a look with a Linux VM.

----------

For the second problem, I think you can keep the library-based build chain for the lib gnomonic stuff. So maybe just go to:

GBVS360-BMS360-ProSal/lib/libgnomonic

And type `make`, I think this should work and you will get a file ".a" in the folder ./bin/

Then you should be able to compile everything from the main makefile at the root folder by just linking the library as it was supposed to be done. 

-----------

I think I will be able to fix that issue within 12-24h... As I don't have too much time for that right now.

**Comment by plebreton** [comment]
Oh, and if you want to quickly solve that problem add all the source as you did and skipping the library-based build maybe you can try to add the ".c" files as you did before with the ".cpp" files, and then add a rule to build ".c" files like:

`

%.o : %.c
(a tabulation) $(CC) $(CFLAGS) -o $@ -c $<

`

**Comment by plebreton** [comment]
OK, it is fixed. 

It was very stupid actually, just the parameters in the last building step which was not in the right order.

https://stackoverflow.com/questions/14613091/cant-link-against-static-library-when-compiling-objects-from-llvm-bitcode#14629673

It looks like it matters on Linux, but does not on macOS.

**Comment by cjhkeep** [comment]
it can build and link success in ubuntu16.04  :)
thx for u help
